

export enum RoleEnum {
    ROLE_SUPER_ADMIN = 'ROLE_SUPER_ADMIN',
    ROLE_PROFESSIONAL = 'ROLE_PROFESSIONAL',
    ROLE_APPOINTMENT_MANAGER = 'ROLE_APPOINTMENT_MANAGER',
    ROLE_ACCOUNTING_MANAGER  = 'ROLE_ACCOUNTING_MANAGER'
}